# Generated by Django 4.0.3 on 2022-04-21 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmback.company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmback.company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmback.company'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmback.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmback.company'),
        ),
    ]
